
services:
  redis:
    image: redis:6
    container_name: redis-training
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    image: ptt-app:latest
    env_file:
      - .env
    container_name: web
    volumes:
      - .:/app
    depends_on:
      - redis
      - mariadb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  celery_worker:
    image: ptt-app:latest
    env_file:
      - .env
    container_name: celery_worker
    depends_on:
      - redis
      - web
    command: celery -A tasks.celery_tasks worker --loglevel=info

  celery_beat:
    image: ptt-app:latest
    env_file:
      - .env
    container_name: celery_beat
    depends_on:
      - redis
      - web
    command: celery -A tasks.celery_tasks beat --loglevel=info

volumes:
  mariadb_data:
